<a href="https://colab.research.google.com/github/Lailson001/E-comerce-modelo/blob/main/Primeira_an%C3%A1lise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

import numpy as np
import matplotlib

No primeiro passo da análise, realizamos uma inspeção geral dos dados utilizando df.info(). Identificamos que o DataFrame contém 12.575 registros e 11 colunas, com diferentes tipos de dados e valores ausentes em algumas colunas, como Item e Discount Applied

In [26]:
df= pd.read_csv("/retail_store_sales.csv")
df.head()
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB
None

Ao indentificar os valores ausentes, usamos cálculos para preenchê-los com dados coerentes. Por exemplo, completamos Total Spent multiplicando Quantity por Price Per Unit. Isso ajuda a manter a consistência das informações.

In [31]:
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity']* df['Price Per Unit'])
df['Price Per Unit'] = df[ 'Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [32]:
df['Calculated Total'] = df['Quantity'] * df['Price Per Unit']

inconsistentes= df[ ]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Calculated Total
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,185.0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,261.0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,43.0
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,247.5
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,87.5